/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Atosl */

#ifndef _Included_Atosl
#define _Included_Atosl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Atosl
 * Method:    symbolicate
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_Atosl_symbolicate
  (JNIEnv *, jobject, jstring, jstring, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
