/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Atosl */

#ifndef _Included_Atosl
#define _Included_Atosl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Atosl
 * Method:    getArchitecture
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Atosl_getArchitecture
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Atosl
 * Method:    symbolicate
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_Atosl_symbolicate
  (JNIEnv *, jobject, jstring, jstring, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
