/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_honeyqa_atosl_Atosl */

#ifndef _Included_io_honeyqa_atosl_Atosl
#define _Included_io_honeyqa_atosl_Atosl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_honeyqa_atosl_Atosl
 * Method:    findArch
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_io_honeyqa_atosl_Atosl_findArch
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_honeyqa_atosl_Atosl
 * Method:    checkUUID
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_io_honeyqa_atosl_Atosl_checkUUID
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     io_honeyqa_atosl_Atosl
 * Method:    symbolicate
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_io_honeyqa_atosl_Atosl_symbolicate
  (JNIEnv *, jobject, jstring, jstring, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
